version: '3.8'

services:
  book_trade_prod:
    image: postgres:13
    container_name: ${DATABASE_CONTAINER_NAME}
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_DB}
    ports:
      - "${DATABASE_PORT}:5432"
    volumes:
      - ${DATABASE_VOLUME}:/var/lib/postgresql/data

  book_trade_dev:
    image: postgres:13
    container_name: ${DATABASE_CONTAINER_NAME}
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_DB}
    ports:
      - "${DATABASE_PORT}:5432"
    volumes:
      - ${DATABASE_VOLUME}:/var/lib/postgresql/data

  book_trade_test:
    image: postgres:13
    container_name: ${DATABASE_CONTAINER_NAME}
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_DB}
    ports:
      - "${DATABASE_PORT}:5432"
    volumes:
      - ${DATABASE_VOLUME}:/var/lib/postgresql/data

volumes:
  book_trade_prod:
  book_trade_dev:
  book_trade_test:
